### ISSUE TITLE
Generate menu automatically

### ISSUE THREAD

**Issue by matthsims** [damofthemoon/vim-leader-mapper#1]
Would you consider an option for generating the menu automatically?
Specifically, using either `nvim_get_keymap` with `nvim_buf_key_keymap`
or
``` vim
redir => maplist
nmap <leader>
redir END
```

This second one requires a fair bit more work and processing on your end, but works in vim too which is obviously preferable.

**Comment by damofthemoon** [comment]
Hello,

I’m brand new to Neovim, I don’t know this function. I’ll take a look tomorrow and implement it. Sounds to be a nice feature for usability and easiness. I’ll update you ASAP. 
Thanks for the tip 👍🏻😄

**Comment by damofthemoon** [comment]
Hi @matthsims,

I took a look to `nvim_get_keymap` and mapped in my leader key `W`to try to catch the mapping. However, I don't see it in the array returned by the function. Sounds none of my leader mapping is listed around there.

About your second suggestion, can you explain please? I don't understand exactly what you got in mind.

**Comment by matthsims** [comment]
Check `:help redir` for a more thorough explanation, it redirects the output of ex commands to something. If you use `=>`, then it will redirect to a variable, which I named `maplist`, but can be any valid variable name of course. When you execute `:nmap <leader>`, you get a list of all mappings that start with your leader, with their `lhs` and `rhs`, and a `*` if it is a buffer local command. So that snippet puts the output of the mapping into a variable, which you could subsequently `split()` on the newlines, and parse out the left hand sides of each mapping.

I don't think this shows if it is otherwise special, like an `<expr>` map, so you could parse out each `lhs` from that list (such as `<space>a`), then use something like `maparg(lhs, 'n', 0, 1) to get a dictionary that describes the mapping. Check out `:help maparg()` of course.

I believe that `nvim_get_keymap('n')` would return a list of all mappings that you could subsequently filter to get the ones you are interested in, but after looking at the output, it might just be easier (and more portable, for vim) to use the `redir` method

**Comment by khalidchawtany** [comment]
You could use `let g:leader_mappings=execute('map <leader>')`
Then you can `:put=g:leader_mappings` to see the result.

**Comment by damofthemoon** [comment]
Thank you @khalidchawtany ! I will give a try to you solution tomorrow and catch leader map to create the menu.

**Comment by damofthemoon** [comment]
Hi folks,

I didn't find a solution to address this request. I would accept a pull request with pleasure if you achieve that 😊 Moreover, I can't figure out how to sort and choose available mapping. Does a user want to map all setup? Just a subset? To be honest, to me that doesn't sound so big to create a dict like explained in the readme to configure the plugin. 

Maybe the user should handle this feature by himself? Opened question... Could you describe more precisely what you got in mind?

**Comment by matthsims** [comment]
Something, more or less, like this was what I had in mind:

``` vim
redir => maplist
nmap <leader>
redir END
let maplist = split(maplist, "\n")
call map(maplist, "split(v:val)")

" contents of maplist (part of mine, for example):
" [ ['n', '<Space>un', '<Plug>(UnicodeSwapCompleteName)']
" ['n', '<Space>h', '*', ':Helptags<CR>']
" ['n', '<Space>A', '*', ':Ag<CR>']
" ['n', '<Space>T', '*', ''':Tags<CR>''', '.', '"''"', '.', 'expand(''<cword>'')', '.', '''', '''']
" ['n', '<Space>t', '*', ':Tags<CR>']
" ['n', '<Space>-', '<Plug>FileBeagleOpenCurrentBufferDir']
" ['n', '<Space>R', '*', ':<C-U>set', 'opfunc=refactor#expression_to_variable<CR>g@']
" ['n', '<Space>do', '*', ':call', 'difference#orig()<CR>']
" ['n', '<Space>ev', '*', ':Files', '$CFGDIR<CR>'] ]

call map(maplist, {_, m -> m[0:1] + (m[2] =~ '\*&@' ? [m[2], join(m[3:])] : [join(m[2:])])})
let ml = '<Space>' " would need to calculate this
call map(maplist, {_, m -> {matchstr(m[1], ml . '\zs.*'): m[2:] + [""]}})

" now looks like:
" [ {'un': ['<Plug>(UnicodeSwapCompleteName)', ""]}
" {'h': ['* :Helptags<CR>', ""]}
" {'A': ['* :Ag<CR>', ""]}
" {'T': ['* '':Tags<CR>'' . "''" . expand(''<cword>'') . '' ''', ""]}
" {'t': ['* :Tags<CR>', ""]}
" {'-': ['<Plug>FileBeagleOpenCurrentBufferDir', ""]}
" {'R': ['* :<C-U>set opfunc=refactor#expression_to_variable<CR>g@', ""]}
" {'do': ['* :call difference#orig()<CR>', ""]}
" {'ev': ['* :Files $CFGDIR<CR>', ""]} ]

```

This is just a quick and dirty example, the third column might be any of `*&@` (see `:h map-listing`), and the third or fourth (depending on the value of the third item) through the end needs to be rejoined with `join()` in certain cases.

The description given by a defined set of mappings is obviously impossible with this setup.

This dictionary is close to the config dict used by your setup, and could pretty easily be modified to get a config, which maybe would be nice to return to the user to allow them to configure the menu. Perhaps putting directly into text, or dumping into a register (`"c` for example)

The info in `:h map-listing` is probably pretty important, though

**Comment by damofthemoon** [comment]
Sounds you are on your way for a pull request 😉 Sorry I don't have time to work on that, but you are welcome if you want to contribute. 

One thing popping my mind while looking at your code is a key is not described, just accompanied by a command that would let the menu ugly if it displays the command in place of the description. We loose here the visual advantage of a leader menu.

**Comment by matthsims** [comment]
You may certainly use that if you like, but I won't be submitting a PR. Time constraints, eh?

And that was what I meant by "The description given by a defined set of mappings is obviously impossible with this setup.", but I definitely see why it was unclear. Sorry about that.

**Comment by damofthemoon** [comment]
No pb. While none of us have time to work on that, I close this issue. Thanks for the proposal. 
Best,
Damien

**Comment by TamaMcGlinn** [comment]
Looks like the similar [vim-which-key](https://github.com/liuchengxu/vim-which-key) already has this feature, making it plug-and-play for those of us coming from the traditional 'remember your own bindings' workflow.
