### ISSUE TITLE
Can it support multi- menus, using different hot key..

### ISSUE THREAD

**Issue by hawkinchina** [damofthemoon/vim-leader-mapper#3]
Can it support multi - menus, using different hot key..
eg. 
\<leader\>fzf:  pop  fZF menus,
\<leader\>vim:  pop vim menus,
\<leader\>xxx:  pop  xxx feature's menu
\<leader\>ggg: pop the global menu, 
and so on. 
when i use different  features, I just pop up the menus that i want.

**Comment by damofthemoon** [comment]
Hi @hawkinchina,

you are describing here something I want to implement, I was just waiting for somebody to ask it, so far so good :).

Supporting sub-menus sounds the good way to address your request, so you could have the global menu opening on leader key pressure, to display FZF menu, vim menu, ... whatever you want to map. Following your example, pressing leader key would open global menu, and FZF could be accessible with `f` for FZF, `v` for Vim, just choose the right key binding.

I think you should be able to creating different calls to access directly to your sub-menus if I add a dictionary argument storing the mapping to the entry function: 

```vim
nnoremap <silent> <leader>f :call leaderMapper#start(g:leaderMenu['f']) "<Space>"<CR>
vnoremap <silent> <leader>f :call leaderMapper#start(g:leaderMenu['f']) "<Space>"<CR> 
```

I'll give a try when I'll implement this feature, likely during the week, else during the weekend. Does it address what you got in mind?

**Comment by hawkinchina** [comment]
That's great....:)

**Comment by damofthemoon** [comment]
Hi there,

I pushed on master the sub-menu support. Please take a look to the README and tell me if it's good to you.

I tried also different binding to call a menu, but I wasn't able to trigger the start function. Anyway now you can pass directly to the start function a menu under JSON format in this way:

```vim
let fzfMenu = {'name':  "",
             \'f': [":Files",                       "FZF file search"],
             \'b': [":Buffers",                  "FZF buffer search"],
             \'s': [":BLines",                   "FZF text search into current buffer"],
             \'S': [":Lines",                     "FZF text search across loaded buffers"],
             \'g': [":BCommits",             "FZF git commits of the current buffer"],
             \'G': [":Commits",               "FZF git commits of the repository"],
             \}

nnoremap <silent> <leader> :call leaderMapper#start(fzfMenu) "<Space>"<CR>
vnoremap <silent> <leader> :call leaderMapper#start(fzfMenu) "<Space>"<CR>
```

Maybe you could try to find how to bind a dedicated to another key binding. For me only space sounds to work, I don't know why 🤔.
